#!/usr/bin/env python3
"""Generate LaTeX rows for the main results table (Table 1) from tracked CSV artifacts.

Scope (current):
- Uses per-model survival summaries under docs/paper/artifacts/tier1_*_survival_summary_*.csv
- Computes persona-UNWEIGHTED aggregates across personas (excluding NRC) for:
  - Survival@5: outputs NRC mean±std, Persona mean±std (across personas), and Δ = Persona − NRC.

Limitations:
- Many summaries currently do not include absolute Fail@1 or Recovery@flip values, only deltas.
  This script therefore leaves those columns as '--' by default.

Usage:
  python3 scripts/gen_latex_table1_from_artifacts.py \
    --out docs/paper/latex_paper_emnlp2023/generated/table1_rows.tex
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS_DIR = REPO_ROOT / "docs" / "paper" / "artifacts"


@dataclass(frozen=True)
class Row:
    model: str
    nrc_surv_mean: float
    nrc_surv_std: float
    persona_surv_mean: float
    persona_surv_std: float


def _read_survival_summary(path: Path) -> tuple[str, list[dict[str, str]]]:
    with path.open("r", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"Empty CSV: {path}")
    model = rows[0]["model"].strip()
    return model, rows


def _mean(xs: Iterable[float]) -> float:
    xs = list(xs)
    if not xs:
        return float("nan")
    return sum(xs) / len(xs)


def _std(xs: Iterable[float]) -> float:
    xs = list(xs)
    if len(xs) <= 1:
        return 0.0
    mu = _mean(xs)
    return math.sqrt(sum((x - mu) ** 2 for x in xs) / (len(xs) - 1))


def _fmt(x: float, digits: int = 3) -> str:
    if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))):
        return "--"
    return f"{x:.{digits}f}"


def _find_latest(pattern: str) -> Path:
    candidates = sorted(ARTIFACTS_DIR.glob(pattern))
    if not candidates:
        raise FileNotFoundError(f"No artifacts match {pattern} under {ARTIFACTS_DIR}")
    # Prefer lexicographically last (date suffix in filename).
    return candidates[-1]


def build_rows(model_to_glob: dict[str, str]) -> list[Row]:
    out: list[Row] = []
    for display, glob_pat in model_to_glob.items():
        p = _find_latest(glob_pat)
        model, rows = _read_survival_summary(p)

        # NRC row
        nrc = [r for r in rows if r["persona"].strip() == "neutral_reask_control"]
        if len(nrc) != 1:
            raise ValueError(f"Expected exactly 1 NRC row in {p}, got {len(nrc)}")
        nrc_surv_mean = float(nrc[0]["survival_r5_mean"])
        nrc_surv_std = float(nrc[0]["survival_r5_std"])

        persona_rows = [r for r in rows if r["persona"].strip() != "neutral_reask_control"]
        surv_means = [float(r["survival_r5_mean"]) for r in persona_rows]
        # Note: This std is across personas (not seeds). Seeds std exists per-persona, but
        # combining std across personas is not well-defined without raw per-seed values.
        persona_surv_mean = _mean(surv_means)
        persona_surv_std = _std(surv_means)

        out.append(
            Row(
                model=display,
                nrc_surv_mean=nrc_surv_mean,
                nrc_surv_std=nrc_surv_std,
                persona_surv_mean=persona_surv_mean,
                persona_surv_std=persona_surv_std,
            )
        )
    return out


def render_table_rows(rows: list[Row]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED. DO NOT EDIT BY HAND.")
    lines.append("% Generated by scripts/gen_latex_table1_from_artifacts.py")
    for r in rows:
        delta = r.persona_surv_mean - r.nrc_surv_mean
        lines.append(
            " ".join(
                [
                    f"{r.model}",
                    "&",
                    f"{_fmt(r.nrc_surv_mean)}$\\pm${_fmt(r.nrc_surv_std)}",
                    "&",
                    f"{_fmt(r.persona_surv_mean)}$\\pm${_fmt(r.persona_surv_std)}",
                    "&",
                    f"{_fmt(delta)}",
                    "&",
                    "-- & -- & --",
                    "&",
                    "-- & -- & --",
                    "\\\\",
                ]
            )
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out",
        required=True,
        help="Output .tex file path (relative to repo root or absolute)",
    )
    args = ap.parse_args()

    # Keep this list aligned with Table~\ref{tab:main} in main.tex.
    # Qwen2.5-7B: we currently track a paper-facing persona-weighted aggregate in Table W.
    # Other families: use the tier1_*_survival_summary_*.csv artifacts.
    model_to_glob = {
        "Llama-3.1-8B-Instruct": "tier1_llama3_8b_seed1-2_survival_summary_*.csv",
        "Mistral-7B-Instruct": "tier1_mistral7b_seed1-2_survival_summary_*.csv",
        "Phi-3-mini-4k-instruct": "tier1_phi3mini_seed1-2_survival_summary_*.csv",
        "Qwen2.5-14B-Instruct": "tier1_qwen2p5_14b_seed1-2_survival_summary_*.csv",
    }

    rows = []

    # Special-case: Qwen2.5-7B from Table W persona-weighted aggregate.
    table_w = _find_latest("table_w_control_vs_persona_seed1-4_mean_std_*.csv")
    with table_w.open("r", newline="") as f:
        tw_rows = list(csv.DictReader(f))
    tw_surv = [r for r in tw_rows if r["metric"].strip() == "Survival@5"]
    if len(tw_surv) != 1:
        raise ValueError(f"Expected exactly 1 Survival@5 row in {table_w}")
    # Table W is in percentage units.
    rows.append(
        Row(
            model="Qwen2.5-7B-Instruct",
            nrc_surv_mean=float(tw_surv[0]["control_mean"]) / 100.0,
            nrc_surv_std=float(tw_surv[0]["control_std"]) / 100.0,
            persona_surv_mean=float(tw_surv[0]["persona_weighted_mean"]) / 100.0,
            persona_surv_std=float(tw_surv[0]["persona_weighted_std"]) / 100.0,
        )
    )

    rows.extend(build_rows(model_to_glob))
    tex = render_table_rows(rows)

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = REPO_ROOT / out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tex, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
